---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
        - op: replace
          path: /spec/acme/email
          value: dasith@ebadfd.tech
        - op: replace
          path: /spec/acme/privateKeySecretRef
          value:
              name: letsencrypt-production
        - op: replace
          path: /spec/acme/solvers
          value: 
            - dns01:
                cloudflare:
                  email: ebadfd@proton.me
                  apiTokenSecretRef:
                    name: cloudflare-token
                    key: cloudflare-token-secret
              selector:
                dnsZones:
                  - "ebadfd.tech"
      target:
        kind: ClusterIssuer
        name: letsencrypt
