apiVersion: traefik.io/v1alpha1 
kind: Middleware
metadata:
  name: default-headers
  namespace: default
spec:
  headers:
    browserXssFilter: true
    customRequestHeaders:
      X-Forwarded-Proto: https
