---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: im-ebadfd-tech-tls-cert
  namespace: matrix
spec:
  secretName: im-ebadfd-tech-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "im.ebadfd.tech"
  dnsNames:
  - "im.ebadfd.tech"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix-synapse
  namespace: matrix
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`im.ebadfd.tech`)
      kind: Rule
      services:
        - name: synapse-matrix-synapse
          kind: Service
          port: 8008
  tls:
    secretName: im-ebadfd-tech-tls
