apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
  labels:
    app: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      hostname: "matrix"
      restartPolicy: "Always"
      securityContext:
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 991
        runAsNonRoot: true
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: "/data/homeserver.yaml"
              subPath: "homeserver.yaml"
              readOnly: true
            - name: synapse-config
              mountPath: "/data/log.config"
              subPath: "log.config"
              readOnly: true
            - name: synapse-secrets
              mountPath: /secrets
              readOnly: true
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: "/data/homeserver.yaml"
            - name: SYNAPSE_REPORT_STATS
              value: "no"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-config
          secret:
            secretName: synapse
        - name: synapse-secrets
          secret:
            secretName: synapse-secrets
