---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: matrix-synapse
  namespace: matrix
spec:
  interval: 1m0s
  url: https://helm.ebadfd.tech
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
  namespace: matrix
spec:
  chart:
    spec:
      chart: matrix-synapse
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: matrix-synapse
      version: v1.0.0
  values:
    serverName: "im.ebadfd.tech"
    publicServerName: "im.ebadfd.tech"
    config:
      reportStats: false
    
    postgresql:
      enabled: false

    externalPostgresql:
      username: synapseadm
      host: 10.20.23.40
      existingSecret: postgres-secrets
      existingSecretPasswordKey: postgres-password

    workers:
      default:
        replicaCount: 2
      generic_worker: 
        enabled: true
      pusher:
        enabled: true
      appservice:
        enabled: true
      media_repository:
        enabled: true
      wellknown: 
        enabled: false

    persistence:
      enabled: true
      annotations: {}
      storageClass: longhorn
      accessMode: ReadWriteMany
      size: 10Gi

    ingress:
      enabled: false

    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: redis-secrets
        existingSecretPasswordKey: redis-password

  interval: 1m0s
