apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
