---
apiVersion: v1
kind: Namespace
metadata:
  name: glance
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: glance
  namespace: glance
spec:
  interval: 1m0s
  url: https://helm.ebadfd.tech
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glance
  namespace: glance
spec:
  chart:
    spec:
      chart: glance
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: glance
      version: v1.0.0
  valuesFiles: 
    - ./values.yml
  interval: 1m0s
