apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx
  - ../base/synapse
  - ../base/glance
patches:
  - path: nginx-values.yaml
    target:
      kind: Deployment
