apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube
  namespace: metube
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  routes:
    - match: Host(`metube.svc.misaki.ebadfd.tech`)
      kind: Rule
      services:
        - name: metube
          kind: Service
          port: 8081
  tls:
    secretName: svc-misaki-ebadfd-tech-tls
