apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance
  namespace: glance
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  routes:
    - match: Host(`homepage.ebadfd.tech`)
      kind: Rule
      services:
        - name: glance
          kind: Service
          port: 8080
